#pragma once

#define RGB_MATRIX_DEFAULT_HUE 5
#define RGB_MATRIX_DEFAULT_SAT 5
// #define ENABLE_RGB_MATRIX_BREATHING	
#define RGBLIGHT_DEFAULT_HUE 5
#define RGBLIGHT_DEFAULT_SAT 5
#define RGBLIGHT_LIMIT_VAL 90
#define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_BREATHING
#define RGBLIGHT_EFFECT_BREATHING 3
